/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pl.betka.infrastructure.kafka.model.avro;
@org.apache.avro.specific.AvroGenerated
public enum AuthenticationStatus implements org.apache.avro.generic.GenericEnumSymbol<AuthenticationStatus> {
  STARTED, AUTHENTICATING, AUTHENTICATED, FAILED, NEEDS_ADDITIONAL_INPUT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AuthenticationStatus\",\"namespace\":\"pl.betka.infrastructure.kafka.model.avro\",\"symbols\":[\"STARTED\",\"AUTHENTICATING\",\"AUTHENTICATED\",\"FAILED\",\"NEEDS_ADDITIONAL_INPUT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
