server:
  port: 8182
spring:
  profiles:
    active: production
  datasource:
    url: jdbc:postgresql://localhost:5432/betka
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true