package pl.betka.connectors.connectors.pl.betclic.fetch.http;

import static com.github.tomakehurst.wiremock.client.WireMock.aResponse;
import static com.github.tomakehurst.wiremock.client.WireMock.equalTo;
import static com.github.tomakehurst.wiremock.client.WireMock.get;
import static com.github.tomakehurst.wiremock.client.WireMock.post;
import static com.github.tomakehurst.wiremock.client.WireMock.stubFor;
import static org.junit.jupiter.api.Assertions.*;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.github.tomakehurst.wiremock.junit5.WireMockRuntimeInfo;
import com.github.tomakehurst.wiremock.junit5.WireMockTest;
import org.apache.hc.client5.http.classic.HttpClient;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.test.context.SpringBootTest;
import pl.betka.connectors.connectors.pl.betclic.HttpAuthenticationConfig;
import pl.betka.connectors.connectors.pl.betclic.authentication.http.BetclicHttpAuthenticationService;
import pl.betka.connectors_configuration.pl.betclic.BetclicHttpAuthenticationData;

@SpringBootTest(classes = {HttpAuthenticationConfig.class})
@WireMockTest(httpPort = 53154)
public class BetclicHttpFetchServiceTest {
  private static final String USERNAME = "dummy_username";
  private static final String PASSWORD = "dummy_password";

  @Autowired
  @Qualifier("integrationTestObjectMapper")
  ObjectMapper objectMapper;

  @Autowired
  @Qualifier("integrationTestHttpClient")
  HttpClient httpClient;

  @Autowired
  @Qualifier("wiremockHost")
  String host;

  @Test
  public void happy_path_register_device(WireMockRuntimeInfo wireMockRuntimeInfo) {
    // given
    BetclicHttpFetchService service = new BetclicHttpFetchService(httpClient, objectMapper);
    BetclicHttpAuthenticationData data =
        BetclicHttpAuthenticationData.builder().username(USERNAME).password(PASSWORD).build();
    createHappyPathRegisterDevice();



    // when
    service.fetchTransactions(data);
//    service.createExcel(null);

    // then

  }

  private void createHappyPathRegisterDevice() {
    stubFor(
        get("/api/v2/me/bets/ended?limit=10&offset=0&embed=Scoreboard&embed=Metagame")
            .withQueryParam("limit", equalTo("10"))
            .withQueryParam("offset", equalTo("0"))
            .withQueryParam("embed", equalTo("Scoreboard"))
            .withQueryParam("embed", equalTo("Metagame"))
            .willReturn(
                aResponse()
                    .withBody(
                        "{\n"
                            + "\t\"bets\": [{\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b9e09b3dbde2cf3376ec5\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2023-06-03T20:09:45.666Z\",\n"
                            + "\t\t\"result\": \"Lose\",\n"
                            + "\t\t\"odds\": 2.3,\n"
                            + "\t\t\"stake\": 46.82,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3495326061,\n"
                            + "\t\t\t\"odds\": 2.3,\n"
                            + "\t\t\t\"selection_label\": \"Tak\",\n"
                            + "\t\t\t\"market_label\": \"Super Kursy\",\n"
                            + "\t\t\t\"match_label\": \"M. Pudzianowski wygra walkę w 1. rundzie (vs A. Szpilka)\",\n"
                            + "\t\t\t\"match_id\": 3001874895,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2023-06-03T20:30:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"*Super Kursy*\",\n"
                            + "\t\t\t\"sport_id\": 99,\n"
                            + "\t\t\t\"competition_label\": \"Super Kursy\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Lose\",\n"
                            + "\t\t\t\"market_id\": 3144265202,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"has_live_streaming\": false,\n"
                            + "\t\t\t\"competition_id\": 25814,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2023-06-03T21:47:18.757Z\",\n"
                            + "\t\t\"tax_on_stake\": 6.38,\n"
                            + "\t\t\"winnings\": 107.69,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b6b1507a1cd09e8f893cf\",\n"
                            + "\t\t\"bet_type\": \"multiple\",\n"
                            + "\t\t\"placed_date_utc\": \"2023-06-03T16:32:21.562Z\",\n"
                            + "\t\t\"result\": \"Lose\",\n"
                            + "\t\t\"odds\": 3.08,\n"
                            + "\t\t\"stake\": 61.6,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3491668383,\n"
                            + "\t\t\t\"odds\": 1.3,\n"
                            + "\t\t\t\"selection_label\": \"Arkadiusz Wrzosek\",\n"
                            + "\t\t\t\"market_label\": \"Zwycięzca walki\",\n"
                            + "\t\t\t\"match_label\": \"Arkadiusz Wrzosek - Bogdan Stoica\",\n"
                            + "\t\t\t\"match_id\": 3001866878,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2023-06-03T20:30:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Sztuki Walki\",\n"
                            + "\t\t\t\"sport_id\": 23,\n"
                            + "\t\t\t\"competition_label\": \"KSW\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Win\",\n"
                            + "\t\t\t\"market_id\": 3143338788,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Arkadiusz Wrzosek\",\n"
                            + "\t\t\t\"contestant2\": \"Bogdan Stoica\",\n"
                            + "\t\t\t\"has_live_streaming\": false,\n"
                            + "\t\t\t\"competition_id\": 4509,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}, {\n"
                            + "\t\t\t\"id\": 3491669323,\n"
                            + "\t\t\t\"odds\": 1.48,\n"
                            + "\t\t\t\"selection_label\": \"Mariusz Pudzianowski\",\n"
                            + "\t\t\t\"market_label\": \"Zwycięzca walki\",\n"
                            + "\t\t\t\"match_label\": \"Mariusz Pudzianowski - Artur Szpilka\",\n"
                            + "\t\t\t\"match_id\": 3001866881,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2023-06-03T21:45:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Sztuki Walki\",\n"
                            + "\t\t\t\"sport_id\": 23,\n"
                            + "\t\t\t\"competition_label\": \"KSW\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Lose\",\n"
                            + "\t\t\t\"market_id\": 3143339100,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Mariusz Pudzianowski\",\n"
                            + "\t\t\t\"contestant2\": \"Artur Szpilka\",\n"
                            + "\t\t\t\"has_live_streaming\": false,\n"
                            + "\t\t\t\"competition_id\": 4509,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}, {\n"
                            + "\t\t\t\"id\": 3491669491,\n"
                            + "\t\t\t\"odds\": 1.6,\n"
                            + "\t\t\t\"selection_label\": \"Mamed Khalidov\",\n"
                            + "\t\t\t\"market_label\": \"Zwycięzca walki\",\n"
                            + "\t\t\t\"match_label\": \"Mamed Khalidov - Scott Askham\",\n"
                            + "\t\t\t\"match_id\": 3001866884,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2023-06-03T22:30:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Sztuki Walki\",\n"
                            + "\t\t\t\"sport_id\": 23,\n"
                            + "\t\t\t\"competition_label\": \"KSW\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Win\",\n"
                            + "\t\t\t\"market_id\": 3143339150,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Mamed Khalidov\",\n"
                            + "\t\t\t\"contestant2\": \"Scott Askham\",\n"
                            + "\t\t\t\"has_live_streaming\": false,\n"
                            + "\t\t\t\"competition_id\": 4509,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2023-06-03T21:45:08.811Z\",\n"
                            + "\t\t\"tax_on_stake\": 8.4,\n"
                            + "\t\t\"winnings\": 189.73,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b6beab3dbde2cf332a007\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2023-06-03T16:35:54.281Z\",\n"
                            + "\t\t\"result\": \"Win\",\n"
                            + "\t\t\"odds\": 2.8,\n"
                            + "\t\t\"stake\": 44.0,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3491663471,\n"
                            + "\t\t\t\"odds\": 2.8,\n"
                            + "\t\t\t\"selection_label\": \"Michał Materla\",\n"
                            + "\t\t\t\"market_label\": \"Zwycięzca walki\",\n"
                            + "\t\t\t\"match_label\": \"Michał Materla - Radosław Paczuski\",\n"
                            + "\t\t\t\"match_id\": 3001866872,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2023-06-03T19:45:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Sztuki Walki\",\n"
                            + "\t\t\t\"sport_id\": 23,\n"
                            + "\t\t\t\"competition_label\": \"KSW\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Win\",\n"
                            + "\t\t\t\"market_id\": 3143337693,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Michał Materla\",\n"
                            + "\t\t\t\"contestant2\": \"Radosław Paczuski\",\n"
                            + "\t\t\t\"has_live_streaming\": false,\n"
                            + "\t\t\t\"competition_id\": 4509,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2023-06-03T19:50:16.992Z\",\n"
                            + "\t\t\"tax_on_stake\": 6.0,\n"
                            + "\t\t\"winnings\": 123.2,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b6618944e0233dc7ce76e\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2023-06-03T16:11:04.068Z\",\n"
                            + "\t\t\"result\": \"Lose\",\n"
                            + "\t\t\"odds\": 6.75,\n"
                            + "\t\t\"stake\": 10.42,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3495313755,\n"
                            + "\t\t\t\"odds\": 6.75,\n"
                            + "\t\t\t\"selection_label\": \"F. Lindgren\",\n"
                            + "\t\t\t\"market_label\": \"Zwycięzca zawodów\",\n"
                            + "\t\t\t\"match_label\": \"GP Czech\",\n"
                            + "\t\t\t\"match_id\": 3001874847,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2023-06-03T17:00:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Żużel\",\n"
                            + "\t\t\t\"sport_id\": 55,\n"
                            + "\t\t\t\"competition_label\": \"GP Czech\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Lose\",\n"
                            + "\t\t\t\"market_id\": 3144261744,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"has_live_streaming\": false,\n"
                            + "\t\t\t\"competition_id\": 3080,\n"
                            + "\t\t\t\"selection_type\": \"live\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2023-06-03T19:41:26.839Z\",\n"
                            + "\t\t\"tax_on_stake\": 1.42,\n"
                            + "\t\t\"winnings\": 70.34,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b4572b3dbde2cf32fe2e2\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2023-06-03T13:51:46.081Z\",\n"
                            + "\t\t\"result\": \"Lose\",\n"
                            + "\t\t\"odds\": 55.0,\n"
                            + "\t\t\"stake\": 4.4,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3492972947,\n"
                            + "\t\t\t\"odds\": 55.0,\n"
                            + "\t\t\t\"selection_label\": \"Bruno Fernandes\",\n"
                            + "\t\t\t\"market_label\": \"Strzelec 2 lub więcej goli\",\n"
                            + "\t\t\t\"match_label\": \"Manchester City - Manchester United\",\n"
                            + "\t\t\t\"match_id\": 3001827936,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2023-06-03T14:00:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Piłka nożna\",\n"
                            + "\t\t\t\"sport_id\": 1,\n"
                            + "\t\t\t\"competition_label\": \"Anglia FA Cup\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Lose\",\n"
                            + "\t\t\t\"market_id\": 3143695890,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Manchester City\",\n"
                            + "\t\t\t\"contestant2\": \"Manchester United\",\n"
                            + "\t\t\t\"has_live_streaming\": true,\n"
                            + "\t\t\t\"competition_id\": 44,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2023-06-03T15:59:04.484Z\",\n"
                            + "\t\t\"tax_on_stake\": 0.6,\n"
                            + "\t\t\"winnings\": 242.0,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b45b9944e0233dc7a9fa8\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2023-06-03T13:52:57.732Z\",\n"
                            + "\t\t\"result\": \"Lose\",\n"
                            + "\t\t\"odds\": 9.0,\n"
                            + "\t\t\"stake\": 8.8,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3470488299,\n"
                            + "\t\t\t\"odds\": 9.0,\n"
                            + "\t\t\t\"selection_label\": \"Manchester United / Manchester United\",\n"
                            + "\t\t\t\"market_label\": \"Wynik Meczu Połowa / Cały\",\n"
                            + "\t\t\t\"match_label\": \"Manchester City - Manchester United\",\n"
                            + "\t\t\t\"match_id\": 3001827936,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2023-06-03T14:00:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Piłka nożna\",\n"
                            + "\t\t\t\"sport_id\": 1,\n"
                            + "\t\t\t\"competition_label\": \"Anglia FA Cup\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Lose\",\n"
                            + "\t\t\t\"market_id\": 3138090366,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Manchester City\",\n"
                            + "\t\t\t\"contestant2\": \"Manchester United\",\n"
                            + "\t\t\t\"has_live_streaming\": true,\n"
                            + "\t\t\t\"competition_id\": 44,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2023-06-03T15:58:43.146Z\",\n"
                            + "\t\t\"tax_on_stake\": 1.2,\n"
                            + "\t\t\"winnings\": 79.2,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b45a8944e0233dc7a9e5f\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2023-06-03T13:52:40.304Z\",\n"
                            + "\t\t\"result\": \"Lose\",\n"
                            + "\t\t\"odds\": 125.0,\n"
                            + "\t\t\"stake\": 4.4,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3492972944,\n"
                            + "\t\t\t\"odds\": 125.0,\n"
                            + "\t\t\t\"selection_label\": \"Casemiro\",\n"
                            + "\t\t\t\"market_label\": \"Strzelec 2 lub więcej goli\",\n"
                            + "\t\t\t\"match_label\": \"Manchester City - Manchester United\",\n"
                            + "\t\t\t\"match_id\": 3001827936,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2023-06-03T14:00:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Piłka nożna\",\n"
                            + "\t\t\t\"sport_id\": 1,\n"
                            + "\t\t\t\"competition_label\": \"Anglia FA Cup\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Lose\",\n"
                            + "\t\t\t\"market_id\": 3143695890,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Manchester City\",\n"
                            + "\t\t\t\"contestant2\": \"Manchester United\",\n"
                            + "\t\t\t\"has_live_streaming\": true,\n"
                            + "\t\t\t\"competition_id\": 44,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2023-06-03T15:58:41.836Z\",\n"
                            + "\t\t\"tax_on_stake\": 0.6,\n"
                            + "\t\t\"winnings\": 550.0,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b45cab3dbde2cf32fe96e\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2023-06-03T13:53:14.378Z\",\n"
                            + "\t\t\"result\": \"Lose\",\n"
                            + "\t\t\"odds\": 13.0,\n"
                            + "\t\t\"stake\": 8.8,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3470487982,\n"
                            + "\t\t\t\"odds\": 13.0,\n"
                            + "\t\t\t\"selection_label\": \"Powyżej 5,5\",\n"
                            + "\t\t\t\"market_label\": \"Gole Powyżej/Poniżej\",\n"
                            + "\t\t\t\"match_label\": \"Manchester City - Manchester United\",\n"
                            + "\t\t\t\"match_id\": 3001827936,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2023-06-03T14:00:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Piłka nożna\",\n"
                            + "\t\t\t\"sport_id\": 1,\n"
                            + "\t\t\t\"competition_label\": \"Anglia FA Cup\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Lose\",\n"
                            + "\t\t\t\"market_id\": 3138090247,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Manchester City\",\n"
                            + "\t\t\t\"contestant2\": \"Manchester United\",\n"
                            + "\t\t\t\"has_live_streaming\": true,\n"
                            + "\t\t\t\"competition_id\": 44,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2023-06-03T15:58:41.311Z\",\n"
                            + "\t\t\"tax_on_stake\": 1.2,\n"
                            + "\t\t\"winnings\": 114.4,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b461a944e0233dc7aa6c4\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2023-06-03T13:54:34.567Z\",\n"
                            + "\t\t\"result\": \"Lose\",\n"
                            + "\t\t\"odds\": 35.0,\n"
                            + "\t\t\"stake\": 4.4,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3492835613,\n"
                            + "\t\t\t\"odds\": 35.0,\n"
                            + "\t\t\t\"selection_label\": \"Raphael Varane\",\n"
                            + "\t\t\t\"market_label\": \"Strzelec\",\n"
                            + "\t\t\t\"match_label\": \"Manchester City - Manchester United\",\n"
                            + "\t\t\t\"match_id\": 3001827936,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2023-06-03T14:00:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Piłka nożna\",\n"
                            + "\t\t\t\"sport_id\": 1,\n"
                            + "\t\t\t\"competition_label\": \"Anglia FA Cup\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Lose\",\n"
                            + "\t\t\t\"market_id\": 3143659667,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Manchester City\",\n"
                            + "\t\t\t\"contestant2\": \"Manchester United\",\n"
                            + "\t\t\t\"has_live_streaming\": true,\n"
                            + "\t\t\t\"competition_id\": 44,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2023-06-03T15:58:40.128Z\",\n"
                            + "\t\t\"tax_on_stake\": 0.6,\n"
                            + "\t\t\"winnings\": 154.0,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b4645a08f492dd564b964\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2023-06-03T13:55:17.095Z\",\n"
                            + "\t\t\"result\": \"Win\",\n"
                            + "\t\t\"odds\": 6.2,\n"
                            + "\t\t\"stake\": 13.2,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3492835617,\n"
                            + "\t\t\t\"odds\": 6.2,\n"
                            + "\t\t\t\"selection_label\": \"Bruno Fernandes\",\n"
                            + "\t\t\t\"market_label\": \"Strzelec\",\n"
                            + "\t\t\t\"match_label\": \"Manchester City - Manchester United\",\n"
                            + "\t\t\t\"match_id\": 3001827936,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2023-06-03T14:00:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Piłka nożna\",\n"
                            + "\t\t\t\"sport_id\": 1,\n"
                            + "\t\t\t\"competition_label\": \"Anglia FA Cup\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Win\",\n"
                            + "\t\t\t\"market_id\": 3143659667,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Manchester City\",\n"
                            + "\t\t\t\"contestant2\": \"Manchester United\",\n"
                            + "\t\t\t\"has_live_streaming\": true,\n"
                            + "\t\t\t\"competition_id\": 44,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2023-06-03T14:36:24.357Z\",\n"
                            + "\t\t\"tax_on_stake\": 1.8,\n"
                            + "\t\t\"winnings\": 81.84,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}]\n"
                            + "}")
                    .withStatus(200)));

    stubFor(
        get("/api/v2/me/bets/ended?limit=10&offset=10&embed=Scoreboard&embed=Metagame")
            .withQueryParam("limit", equalTo("10"))
            .withQueryParam("offset", equalTo("10"))
            .withQueryParam("embed", equalTo("Scoreboard"))
            .withQueryParam("embed", equalTo("Metagame"))
            .willReturn(
                aResponse()
                    .withBody(
                        "{\n"
                            + "\t\"bets\": [{\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b9e09b3dbde2cf3376ec5\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2023-06-03T20:09:45.666Z\",\n"
                            + "\t\t\"result\": \"Lose\",\n"
                            + "\t\t\"odds\": 2.3,\n"
                            + "\t\t\"stake\": 46.82,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3495326061,\n"
                            + "\t\t\t\"odds\": 2.3,\n"
                            + "\t\t\t\"selection_label\": \"Tak\",\n"
                            + "\t\t\t\"market_label\": \"Super Kursy\",\n"
                            + "\t\t\t\"match_label\": \"M. Pudzianowski wygra walkę w 1. rundzie (vs A. Szpilka)\",\n"
                            + "\t\t\t\"match_id\": 3001874895,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2023-06-03T20:30:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"*Super Kursy*\",\n"
                            + "\t\t\t\"sport_id\": 99,\n"
                            + "\t\t\t\"competition_label\": \"Super Kursy\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Lose\",\n"
                            + "\t\t\t\"market_id\": 3144265202,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"has_live_streaming\": false,\n"
                            + "\t\t\t\"competition_id\": 25814,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2023-06-03T21:47:18.757Z\",\n"
                            + "\t\t\"tax_on_stake\": 6.38,\n"
                            + "\t\t\"winnings\": 107.69,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b6b1507a1cd09e8f893cf\",\n"
                            + "\t\t\"bet_type\": \"multiple\",\n"
                            + "\t\t\"placed_date_utc\": \"2023-06-03T16:32:21.562Z\",\n"
                            + "\t\t\"result\": \"Lose\",\n"
                            + "\t\t\"odds\": 3.08,\n"
                            + "\t\t\"stake\": 61.6,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3491668383,\n"
                            + "\t\t\t\"odds\": 1.3,\n"
                            + "\t\t\t\"selection_label\": \"Arkadiusz Wrzosek\",\n"
                            + "\t\t\t\"market_label\": \"Zwycięzca walki\",\n"
                            + "\t\t\t\"match_label\": \"Arkadiusz Wrzosek - Bogdan Stoica\",\n"
                            + "\t\t\t\"match_id\": 3001866878,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2023-06-03T20:30:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Sztuki Walki\",\n"
                            + "\t\t\t\"sport_id\": 23,\n"
                            + "\t\t\t\"competition_label\": \"KSW\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Win\",\n"
                            + "\t\t\t\"market_id\": 3143338788,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Arkadiusz Wrzosek\",\n"
                            + "\t\t\t\"contestant2\": \"Bogdan Stoica\",\n"
                            + "\t\t\t\"has_live_streaming\": false,\n"
                            + "\t\t\t\"competition_id\": 4509,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}, {\n"
                            + "\t\t\t\"id\": 3491669323,\n"
                            + "\t\t\t\"odds\": 1.48,\n"
                            + "\t\t\t\"selection_label\": \"Mariusz Pudzianowski\",\n"
                            + "\t\t\t\"market_label\": \"Zwycięzca walki\",\n"
                            + "\t\t\t\"match_label\": \"Mariusz Pudzianowski - Artur Szpilka\",\n"
                            + "\t\t\t\"match_id\": 3001866881,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2023-06-03T21:45:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Sztuki Walki\",\n"
                            + "\t\t\t\"sport_id\": 23,\n"
                            + "\t\t\t\"competition_label\": \"KSW\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Lose\",\n"
                            + "\t\t\t\"market_id\": 3143339100,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Mariusz Pudzianowski\",\n"
                            + "\t\t\t\"contestant2\": \"Artur Szpilka\",\n"
                            + "\t\t\t\"has_live_streaming\": false,\n"
                            + "\t\t\t\"competition_id\": 4509,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}, {\n"
                            + "\t\t\t\"id\": 3491669491,\n"
                            + "\t\t\t\"odds\": 1.6,\n"
                            + "\t\t\t\"selection_label\": \"Mamed Khalidov\",\n"
                            + "\t\t\t\"market_label\": \"Zwycięzca walki\",\n"
                            + "\t\t\t\"match_label\": \"Mamed Khalidov - Scott Askham\",\n"
                            + "\t\t\t\"match_id\": 3001866884,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2023-06-03T22:30:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Sztuki Walki\",\n"
                            + "\t\t\t\"sport_id\": 23,\n"
                            + "\t\t\t\"competition_label\": \"KSW\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Win\",\n"
                            + "\t\t\t\"market_id\": 3143339150,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Mamed Khalidov\",\n"
                            + "\t\t\t\"contestant2\": \"Scott Askham\",\n"
                            + "\t\t\t\"has_live_streaming\": false,\n"
                            + "\t\t\t\"competition_id\": 4509,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2023-06-03T21:45:08.811Z\",\n"
                            + "\t\t\"tax_on_stake\": 8.4,\n"
                            + "\t\t\"winnings\": 189.73,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b6beab3dbde2cf332a007\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2023-06-03T16:35:54.281Z\",\n"
                            + "\t\t\"result\": \"Win\",\n"
                            + "\t\t\"odds\": 2.8,\n"
                            + "\t\t\"stake\": 44.0,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3491663471,\n"
                            + "\t\t\t\"odds\": 2.8,\n"
                            + "\t\t\t\"selection_label\": \"Michał Materla\",\n"
                            + "\t\t\t\"market_label\": \"Zwycięzca walki\",\n"
                            + "\t\t\t\"match_label\": \"Michał Materla - Radosław Paczuski\",\n"
                            + "\t\t\t\"match_id\": 3001866872,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2023-06-03T19:45:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Sztuki Walki\",\n"
                            + "\t\t\t\"sport_id\": 23,\n"
                            + "\t\t\t\"competition_label\": \"KSW\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Win\",\n"
                            + "\t\t\t\"market_id\": 3143337693,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Michał Materla\",\n"
                            + "\t\t\t\"contestant2\": \"Radosław Paczuski\",\n"
                            + "\t\t\t\"has_live_streaming\": false,\n"
                            + "\t\t\t\"competition_id\": 4509,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2023-06-03T19:50:16.992Z\",\n"
                            + "\t\t\"tax_on_stake\": 6.0,\n"
                            + "\t\t\"winnings\": 123.2,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b6618944e0233dc7ce76e\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2023-06-03T16:11:04.068Z\",\n"
                            + "\t\t\"result\": \"Lose\",\n"
                            + "\t\t\"odds\": 6.75,\n"
                            + "\t\t\"stake\": 10.42,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3495313755,\n"
                            + "\t\t\t\"odds\": 6.75,\n"
                            + "\t\t\t\"selection_label\": \"F. Lindgren\",\n"
                            + "\t\t\t\"market_label\": \"Zwycięzca zawodów\",\n"
                            + "\t\t\t\"match_label\": \"GP Czech\",\n"
                            + "\t\t\t\"match_id\": 3001874847,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2023-06-03T17:00:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Żużel\",\n"
                            + "\t\t\t\"sport_id\": 55,\n"
                            + "\t\t\t\"competition_label\": \"GP Czech\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Lose\",\n"
                            + "\t\t\t\"market_id\": 3144261744,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"has_live_streaming\": false,\n"
                            + "\t\t\t\"competition_id\": 3080,\n"
                            + "\t\t\t\"selection_type\": \"live\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2023-06-03T19:41:26.839Z\",\n"
                            + "\t\t\"tax_on_stake\": 1.42,\n"
                            + "\t\t\"winnings\": 70.34,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b4572b3dbde2cf32fe2e2\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2023-06-03T13:51:46.081Z\",\n"
                            + "\t\t\"result\": \"Lose\",\n"
                            + "\t\t\"odds\": 55.0,\n"
                            + "\t\t\"stake\": 4.4,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3492972947,\n"
                            + "\t\t\t\"odds\": 55.0,\n"
                            + "\t\t\t\"selection_label\": \"Bruno Fernandes\",\n"
                            + "\t\t\t\"market_label\": \"Strzelec 2 lub więcej goli\",\n"
                            + "\t\t\t\"match_label\": \"Manchester City - Manchester United\",\n"
                            + "\t\t\t\"match_id\": 3001827936,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2023-06-03T14:00:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Piłka nożna\",\n"
                            + "\t\t\t\"sport_id\": 1,\n"
                            + "\t\t\t\"competition_label\": \"Anglia FA Cup\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Lose\",\n"
                            + "\t\t\t\"market_id\": 3143695890,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Manchester City\",\n"
                            + "\t\t\t\"contestant2\": \"Manchester United\",\n"
                            + "\t\t\t\"has_live_streaming\": true,\n"
                            + "\t\t\t\"competition_id\": 44,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2023-06-03T15:59:04.484Z\",\n"
                            + "\t\t\"tax_on_stake\": 0.6,\n"
                            + "\t\t\"winnings\": 242.0,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b45b9944e0233dc7a9fa8\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2023-06-03T13:52:57.732Z\",\n"
                            + "\t\t\"result\": \"Lose\",\n"
                            + "\t\t\"odds\": 9.0,\n"
                            + "\t\t\"stake\": 8.8,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3470488299,\n"
                            + "\t\t\t\"odds\": 9.0,\n"
                            + "\t\t\t\"selection_label\": \"Manchester United / Manchester United\",\n"
                            + "\t\t\t\"market_label\": \"Wynik Meczu Połowa / Cały\",\n"
                            + "\t\t\t\"match_label\": \"Manchester City - Manchester United\",\n"
                            + "\t\t\t\"match_id\": 3001827936,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2023-06-03T14:00:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Piłka nożna\",\n"
                            + "\t\t\t\"sport_id\": 1,\n"
                            + "\t\t\t\"competition_label\": \"Anglia FA Cup\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Lose\",\n"
                            + "\t\t\t\"market_id\": 3138090366,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Manchester City\",\n"
                            + "\t\t\t\"contestant2\": \"Manchester United\",\n"
                            + "\t\t\t\"has_live_streaming\": true,\n"
                            + "\t\t\t\"competition_id\": 44,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2023-06-03T15:58:43.146Z\",\n"
                            + "\t\t\"tax_on_stake\": 1.2,\n"
                            + "\t\t\"winnings\": 79.2,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b45a8944e0233dc7a9e5f\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2023-06-03T13:52:40.304Z\",\n"
                            + "\t\t\"result\": \"Lose\",\n"
                            + "\t\t\"odds\": 125.0,\n"
                            + "\t\t\"stake\": 4.4,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3492972944,\n"
                            + "\t\t\t\"odds\": 125.0,\n"
                            + "\t\t\t\"selection_label\": \"Casemiro\",\n"
                            + "\t\t\t\"market_label\": \"Strzelec 2 lub więcej goli\",\n"
                            + "\t\t\t\"match_label\": \"Manchester City - Manchester United\",\n"
                            + "\t\t\t\"match_id\": 3001827936,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2023-06-03T14:00:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Piłka nożna\",\n"
                            + "\t\t\t\"sport_id\": 1,\n"
                            + "\t\t\t\"competition_label\": \"Anglia FA Cup\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Lose\",\n"
                            + "\t\t\t\"market_id\": 3143695890,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Manchester City\",\n"
                            + "\t\t\t\"contestant2\": \"Manchester United\",\n"
                            + "\t\t\t\"has_live_streaming\": true,\n"
                            + "\t\t\t\"competition_id\": 44,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2023-06-03T15:58:41.836Z\",\n"
                            + "\t\t\"tax_on_stake\": 0.6,\n"
                            + "\t\t\"winnings\": 550.0,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b45cab3dbde2cf32fe96e\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2023-06-03T13:53:14.378Z\",\n"
                            + "\t\t\"result\": \"Lose\",\n"
                            + "\t\t\"odds\": 13.0,\n"
                            + "\t\t\"stake\": 8.8,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3470487982,\n"
                            + "\t\t\t\"odds\": 13.0,\n"
                            + "\t\t\t\"selection_label\": \"Powyżej 5,5\",\n"
                            + "\t\t\t\"market_label\": \"Gole Powyżej/Poniżej\",\n"
                            + "\t\t\t\"match_label\": \"Manchester City - Manchester United\",\n"
                            + "\t\t\t\"match_id\": 3001827936,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2023-06-03T14:00:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Piłka nożna\",\n"
                            + "\t\t\t\"sport_id\": 1,\n"
                            + "\t\t\t\"competition_label\": \"Anglia FA Cup\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Lose\",\n"
                            + "\t\t\t\"market_id\": 3138090247,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Manchester City\",\n"
                            + "\t\t\t\"contestant2\": \"Manchester United\",\n"
                            + "\t\t\t\"has_live_streaming\": true,\n"
                            + "\t\t\t\"competition_id\": 44,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2023-06-03T15:58:41.311Z\",\n"
                            + "\t\t\"tax_on_stake\": 1.2,\n"
                            + "\t\t\"winnings\": 114.4,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b461a944e0233dc7aa6c4\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2023-06-03T13:54:34.567Z\",\n"
                            + "\t\t\"result\": \"Lose\",\n"
                            + "\t\t\"odds\": 35.0,\n"
                            + "\t\t\"stake\": 4.4,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3492835613,\n"
                            + "\t\t\t\"odds\": 35.0,\n"
                            + "\t\t\t\"selection_label\": \"Raphael Varane\",\n"
                            + "\t\t\t\"market_label\": \"Strzelec\",\n"
                            + "\t\t\t\"match_label\": \"Manchester City - Manchester United\",\n"
                            + "\t\t\t\"match_id\": 3001827936,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2023-06-03T14:00:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Piłka nożna\",\n"
                            + "\t\t\t\"sport_id\": 1,\n"
                            + "\t\t\t\"competition_label\": \"Anglia FA Cup\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Lose\",\n"
                            + "\t\t\t\"market_id\": 3143659667,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Manchester City\",\n"
                            + "\t\t\t\"contestant2\": \"Manchester United\",\n"
                            + "\t\t\t\"has_live_streaming\": true,\n"
                            + "\t\t\t\"competition_id\": 44,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2023-06-03T15:58:40.128Z\",\n"
                            + "\t\t\"tax_on_stake\": 0.6,\n"
                            + "\t\t\"winnings\": 154.0,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b4645a08f492dd564b964\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2023-06-03T13:55:17.095Z\",\n"
                            + "\t\t\"result\": \"Win\",\n"
                            + "\t\t\"odds\": 6.2,\n"
                            + "\t\t\"stake\": 13.2,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3492835617,\n"
                            + "\t\t\t\"odds\": 6.2,\n"
                            + "\t\t\t\"selection_label\": \"Bruno Fernandes\",\n"
                            + "\t\t\t\"market_label\": \"Strzelec\",\n"
                            + "\t\t\t\"match_label\": \"Manchester City - Manchester United\",\n"
                            + "\t\t\t\"match_id\": 3001827936,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2023-06-03T14:00:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Piłka nożna\",\n"
                            + "\t\t\t\"sport_id\": 1,\n"
                            + "\t\t\t\"competition_label\": \"Anglia FA Cup\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Win\",\n"
                            + "\t\t\t\"market_id\": 3143659667,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Manchester City\",\n"
                            + "\t\t\t\"contestant2\": \"Manchester United\",\n"
                            + "\t\t\t\"has_live_streaming\": true,\n"
                            + "\t\t\t\"competition_id\": 44,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2023-06-03T14:36:24.357Z\",\n"
                            + "\t\t\"tax_on_stake\": 1.8,\n"
                            + "\t\t\"winnings\": 81.84,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}]\n"
                            + "}")
                    .withStatus(200)));
    stubFor(
        get("/api/v2/me/bets/ended?limit=10&offset=20&embed=Scoreboard&embed=Metagame")
            .withQueryParam("limit", equalTo("10"))
            .withQueryParam("offset", equalTo("20"))
            .withQueryParam("embed", equalTo("Scoreboard"))
            .withQueryParam("embed", equalTo("Metagame"))
            .willReturn(
                aResponse()
                    .withBody(
                        "{\n"
                            + "\t\"bets\": [{\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b9e09b3dbde2cf3376ec5\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2021-06-03T20:09:45.666Z\",\n"
                            + "\t\t\"result\": \"Lose\",\n"
                            + "\t\t\"odds\": 2.3,\n"
                            + "\t\t\"stake\": 46.82,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3495326061,\n"
                            + "\t\t\t\"odds\": 2.3,\n"
                            + "\t\t\t\"selection_label\": \"Tak\",\n"
                            + "\t\t\t\"market_label\": \"Super Kursy\",\n"
                            + "\t\t\t\"match_label\": \"M. Pudzianowski wygra walkę w 1. rundzie (vs A. Szpilka)\",\n"
                            + "\t\t\t\"match_id\": 3001874895,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2021-06-03T20:30:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"*Super Kursy*\",\n"
                            + "\t\t\t\"sport_id\": 99,\n"
                            + "\t\t\t\"competition_label\": \"Super Kursy\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Lose\",\n"
                            + "\t\t\t\"market_id\": 3144265202,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"has_live_streaming\": false,\n"
                            + "\t\t\t\"competition_id\": 25814,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2021-06-03T21:47:18.757Z\",\n"
                            + "\t\t\"tax_on_stake\": 6.38,\n"
                            + "\t\t\"winnings\": 107.69,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b6b1507a1cd09e8f893cf\",\n"
                            + "\t\t\"bet_type\": \"multiple\",\n"
                            + "\t\t\"placed_date_utc\": \"2021-06-03T16:32:21.562Z\",\n"
                            + "\t\t\"result\": \"Lose\",\n"
                            + "\t\t\"odds\": 3.08,\n"
                            + "\t\t\"stake\": 61.6,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3491668383,\n"
                            + "\t\t\t\"odds\": 1.3,\n"
                            + "\t\t\t\"selection_label\": \"Arkadiusz Wrzosek\",\n"
                            + "\t\t\t\"market_label\": \"Zwycięzca walki\",\n"
                            + "\t\t\t\"match_label\": \"Arkadiusz Wrzosek - Bogdan Stoica\",\n"
                            + "\t\t\t\"match_id\": 3001866878,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2021-06-03T20:30:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Sztuki Walki\",\n"
                            + "\t\t\t\"sport_id\": 23,\n"
                            + "\t\t\t\"competition_label\": \"KSW\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Win\",\n"
                            + "\t\t\t\"market_id\": 3143338788,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Arkadiusz Wrzosek\",\n"
                            + "\t\t\t\"contestant2\": \"Bogdan Stoica\",\n"
                            + "\t\t\t\"has_live_streaming\": false,\n"
                            + "\t\t\t\"competition_id\": 4509,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}, {\n"
                            + "\t\t\t\"id\": 3491669323,\n"
                            + "\t\t\t\"odds\": 1.48,\n"
                            + "\t\t\t\"selection_label\": \"Mariusz Pudzianowski\",\n"
                            + "\t\t\t\"market_label\": \"Zwycięzca walki\",\n"
                            + "\t\t\t\"match_label\": \"Mariusz Pudzianowski - Artur Szpilka\",\n"
                            + "\t\t\t\"match_id\": 3001866881,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2021-06-03T21:45:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Sztuki Walki\",\n"
                            + "\t\t\t\"sport_id\": 23,\n"
                            + "\t\t\t\"competition_label\": \"KSW\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Lose\",\n"
                            + "\t\t\t\"market_id\": 3143339100,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Mariusz Pudzianowski\",\n"
                            + "\t\t\t\"contestant2\": \"Artur Szpilka\",\n"
                            + "\t\t\t\"has_live_streaming\": false,\n"
                            + "\t\t\t\"competition_id\": 4509,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}, {\n"
                            + "\t\t\t\"id\": 3491669491,\n"
                            + "\t\t\t\"odds\": 1.6,\n"
                            + "\t\t\t\"selection_label\": \"Mamed Khalidov\",\n"
                            + "\t\t\t\"market_label\": \"Zwycięzca walki\",\n"
                            + "\t\t\t\"match_label\": \"Mamed Khalidov - Scott Askham\",\n"
                            + "\t\t\t\"match_id\": 3001866884,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2021-06-03T22:30:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Sztuki Walki\",\n"
                            + "\t\t\t\"sport_id\": 23,\n"
                            + "\t\t\t\"competition_label\": \"KSW\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Win\",\n"
                            + "\t\t\t\"market_id\": 3143339150,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Mamed Khalidov\",\n"
                            + "\t\t\t\"contestant2\": \"Scott Askham\",\n"
                            + "\t\t\t\"has_live_streaming\": false,\n"
                            + "\t\t\t\"competition_id\": 4509,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2021-06-03T21:45:08.811Z\",\n"
                            + "\t\t\"tax_on_stake\": 8.4,\n"
                            + "\t\t\"winnings\": 189.73,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b6beab3dbde2cf332a007\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2021-06-03T16:35:54.281Z\",\n"
                            + "\t\t\"result\": \"Win\",\n"
                            + "\t\t\"odds\": 2.8,\n"
                            + "\t\t\"stake\": 44.0,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3491663471,\n"
                            + "\t\t\t\"odds\": 2.8,\n"
                            + "\t\t\t\"selection_label\": \"Michał Materla\",\n"
                            + "\t\t\t\"market_label\": \"Zwycięzca walki\",\n"
                            + "\t\t\t\"match_label\": \"Michał Materla - Radosław Paczuski\",\n"
                            + "\t\t\t\"match_id\": 3001866872,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2021-06-03T19:45:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Sztuki Walki\",\n"
                            + "\t\t\t\"sport_id\": 23,\n"
                            + "\t\t\t\"competition_label\": \"KSW\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Win\",\n"
                            + "\t\t\t\"market_id\": 3143337693,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Michał Materla\",\n"
                            + "\t\t\t\"contestant2\": \"Radosław Paczuski\",\n"
                            + "\t\t\t\"has_live_streaming\": false,\n"
                            + "\t\t\t\"competition_id\": 4509,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2021-06-03T19:50:16.992Z\",\n"
                            + "\t\t\"tax_on_stake\": 6.0,\n"
                            + "\t\t\"winnings\": 123.2,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b6618944e0233dc7ce76e\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2021-06-03T16:11:04.068Z\",\n"
                            + "\t\t\"result\": \"Lose\",\n"
                            + "\t\t\"odds\": 6.75,\n"
                            + "\t\t\"stake\": 10.42,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3495313755,\n"
                            + "\t\t\t\"odds\": 6.75,\n"
                            + "\t\t\t\"selection_label\": \"F. Lindgren\",\n"
                            + "\t\t\t\"market_label\": \"Zwycięzca zawodów\",\n"
                            + "\t\t\t\"match_label\": \"GP Czech\",\n"
                            + "\t\t\t\"match_id\": 3001874847,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2021-06-03T17:00:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Żużel\",\n"
                            + "\t\t\t\"sport_id\": 55,\n"
                            + "\t\t\t\"competition_label\": \"GP Czech\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Lose\",\n"
                            + "\t\t\t\"market_id\": 3144261744,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"has_live_streaming\": false,\n"
                            + "\t\t\t\"competition_id\": 3080,\n"
                            + "\t\t\t\"selection_type\": \"live\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2021-06-03T19:41:26.839Z\",\n"
                            + "\t\t\"tax_on_stake\": 1.42,\n"
                            + "\t\t\"winnings\": 70.34,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b4572b3dbde2cf32fe2e2\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2021-06-03T13:51:46.081Z\",\n"
                            + "\t\t\"result\": \"Lose\",\n"
                            + "\t\t\"odds\": 55.0,\n"
                            + "\t\t\"stake\": 4.4,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3492972947,\n"
                            + "\t\t\t\"odds\": 55.0,\n"
                            + "\t\t\t\"selection_label\": \"Bruno Fernandes\",\n"
                            + "\t\t\t\"market_label\": \"Strzelec 2 lub więcej goli\",\n"
                            + "\t\t\t\"match_label\": \"Manchester City - Manchester United\",\n"
                            + "\t\t\t\"match_id\": 3001827936,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2021-06-03T14:00:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Piłka nożna\",\n"
                            + "\t\t\t\"sport_id\": 1,\n"
                            + "\t\t\t\"competition_label\": \"Anglia FA Cup\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Lose\",\n"
                            + "\t\t\t\"market_id\": 3143695890,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Manchester City\",\n"
                            + "\t\t\t\"contestant2\": \"Manchester United\",\n"
                            + "\t\t\t\"has_live_streaming\": true,\n"
                            + "\t\t\t\"competition_id\": 44,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2021-06-03T15:59:04.484Z\",\n"
                            + "\t\t\"tax_on_stake\": 0.6,\n"
                            + "\t\t\"winnings\": 242.0,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b45b9944e0233dc7a9fa8\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2021-06-03T13:52:57.732Z\",\n"
                            + "\t\t\"result\": \"Lose\",\n"
                            + "\t\t\"odds\": 9.0,\n"
                            + "\t\t\"stake\": 8.8,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3470488299,\n"
                            + "\t\t\t\"odds\": 9.0,\n"
                            + "\t\t\t\"selection_label\": \"Manchester United / Manchester United\",\n"
                            + "\t\t\t\"market_label\": \"Wynik Meczu Połowa / Cały\",\n"
                            + "\t\t\t\"match_label\": \"Manchester City - Manchester United\",\n"
                            + "\t\t\t\"match_id\": 3001827936,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2021-06-03T14:00:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Piłka nożna\",\n"
                            + "\t\t\t\"sport_id\": 1,\n"
                            + "\t\t\t\"competition_label\": \"Anglia FA Cup\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Lose\",\n"
                            + "\t\t\t\"market_id\": 3138090366,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Manchester City\",\n"
                            + "\t\t\t\"contestant2\": \"Manchester United\",\n"
                            + "\t\t\t\"has_live_streaming\": true,\n"
                            + "\t\t\t\"competition_id\": 44,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2021-06-03T15:58:43.146Z\",\n"
                            + "\t\t\"tax_on_stake\": 1.2,\n"
                            + "\t\t\"winnings\": 79.2,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b45a8944e0233dc7a9e5f\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2021-06-03T13:52:40.304Z\",\n"
                            + "\t\t\"result\": \"Lose\",\n"
                            + "\t\t\"odds\": 125.0,\n"
                            + "\t\t\"stake\": 4.4,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3492972944,\n"
                            + "\t\t\t\"odds\": 125.0,\n"
                            + "\t\t\t\"selection_label\": \"Casemiro\",\n"
                            + "\t\t\t\"market_label\": \"Strzelec 2 lub więcej goli\",\n"
                            + "\t\t\t\"match_label\": \"Manchester City - Manchester United\",\n"
                            + "\t\t\t\"match_id\": 3001827936,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2021-06-03T14:00:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Piłka nożna\",\n"
                            + "\t\t\t\"sport_id\": 1,\n"
                            + "\t\t\t\"competition_label\": \"Anglia FA Cup\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Lose\",\n"
                            + "\t\t\t\"market_id\": 3143695890,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Manchester City\",\n"
                            + "\t\t\t\"contestant2\": \"Manchester United\",\n"
                            + "\t\t\t\"has_live_streaming\": true,\n"
                            + "\t\t\t\"competition_id\": 44,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2021-06-03T15:58:41.836Z\",\n"
                            + "\t\t\"tax_on_stake\": 0.6,\n"
                            + "\t\t\"winnings\": 550.0,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b45cab3dbde2cf32fe96e\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2021-06-03T13:53:14.378Z\",\n"
                            + "\t\t\"result\": \"Lose\",\n"
                            + "\t\t\"odds\": 13.0,\n"
                            + "\t\t\"stake\": 8.8,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3470487982,\n"
                            + "\t\t\t\"odds\": 13.0,\n"
                            + "\t\t\t\"selection_label\": \"Powyżej 5,5\",\n"
                            + "\t\t\t\"market_label\": \"Gole Powyżej/Poniżej\",\n"
                            + "\t\t\t\"match_label\": \"Manchester City - Manchester United\",\n"
                            + "\t\t\t\"match_id\": 3001827936,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2021-06-03T14:00:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Piłka nożna\",\n"
                            + "\t\t\t\"sport_id\": 1,\n"
                            + "\t\t\t\"competition_label\": \"Anglia FA Cup\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Lose\",\n"
                            + "\t\t\t\"market_id\": 3138090247,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Manchester City\",\n"
                            + "\t\t\t\"contestant2\": \"Manchester United\",\n"
                            + "\t\t\t\"has_live_streaming\": true,\n"
                            + "\t\t\t\"competition_id\": 44,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2021-06-03T15:58:41.311Z\",\n"
                            + "\t\t\"tax_on_stake\": 1.2,\n"
                            + "\t\t\"winnings\": 114.4,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b461a944e0233dc7aa6c4\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2021-06-03T13:54:34.567Z\",\n"
                            + "\t\t\"result\": \"Lose\",\n"
                            + "\t\t\"odds\": 35.0,\n"
                            + "\t\t\"stake\": 4.4,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3492835613,\n"
                            + "\t\t\t\"odds\": 35.0,\n"
                            + "\t\t\t\"selection_label\": \"Raphael Varane\",\n"
                            + "\t\t\t\"market_label\": \"Strzelec\",\n"
                            + "\t\t\t\"match_label\": \"Manchester City - Manchester United\",\n"
                            + "\t\t\t\"match_id\": 3001827936,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2021-06-03T14:00:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Piłka nożna\",\n"
                            + "\t\t\t\"sport_id\": 1,\n"
                            + "\t\t\t\"competition_label\": \"Anglia FA Cup\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Lose\",\n"
                            + "\t\t\t\"market_id\": 3143659667,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Manchester City\",\n"
                            + "\t\t\t\"contestant2\": \"Manchester United\",\n"
                            + "\t\t\t\"has_live_streaming\": true,\n"
                            + "\t\t\t\"competition_id\": 44,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2021-06-03T15:58:40.128Z\",\n"
                            + "\t\t\"tax_on_stake\": 0.6,\n"
                            + "\t\t\"winnings\": 154.0,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}, {\n"
                            + "\t\t\"id\": -1,\n"
                            + "\t\t\"bet_reference\": \"647b4645a08f492dd564b964\",\n"
                            + "\t\t\"bet_type\": \"simple\",\n"
                            + "\t\t\"placed_date_utc\": \"2021-06-03T13:55:17.095Z\",\n"
                            + "\t\t\"result\": \"Win\",\n"
                            + "\t\t\"odds\": 6.2,\n"
                            + "\t\t\"stake\": 13.2,\n"
                            + "\t\t\"is_freebet\": false,\n"
                            + "\t\t\"bet_selections\": [{\n"
                            + "\t\t\t\"id\": 3492835617,\n"
                            + "\t\t\t\"odds\": 6.2,\n"
                            + "\t\t\t\"selection_label\": \"Bruno Fernandes\",\n"
                            + "\t\t\t\"market_label\": \"Strzelec\",\n"
                            + "\t\t\t\"match_label\": \"Manchester City - Manchester United\",\n"
                            + "\t\t\t\"match_id\": 3001827936,\n"
                            + "\t\t\t\"match_status\": \"ended\",\n"
                            + "\t\t\t\"match_date_utc\": \"2021-06-03T14:00:00Z\",\n"
                            + "\t\t\t\"sport_label\": \"Piłka nożna\",\n"
                            + "\t\t\t\"sport_id\": 1,\n"
                            + "\t\t\t\"competition_label\": \"Anglia FA Cup\",\n"
                            + "\t\t\t\"is_boosted_odd\": false,\n"
                            + "\t\t\t\"result\": \"Win\",\n"
                            + "\t\t\t\"market_id\": 3143659667,\n"
                            + "\t\t\t\"is_mbb_eligible\": false,\n"
                            + "\t\t\t\"contestant1\": \"Manchester City\",\n"
                            + "\t\t\t\"contestant2\": \"Manchester United\",\n"
                            + "\t\t\t\"has_live_streaming\": true,\n"
                            + "\t\t\t\"competition_id\": 44,\n"
                            + "\t\t\t\"selection_type\": \"prematch\"\n"
                            + "\t\t}],\n"
                            + "\t\t\"is_awaiting_payment\": false,\n"
                            + "\t\t\"closed_date_utc\": \"2021-06-03T14:36:24.357Z\",\n"
                            + "\t\t\"tax_on_stake\": 1.8,\n"
                            + "\t\t\"winnings\": 81.84,\n"
                            + "\t\t\"metagame\": {}\n"
                            + "\t}]\n"
                            + "}")
                    .withStatus(200)));
  }
}
